name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: install
        run: yarn install
      - name: typescript check
        run: yarn lint:tsc
      - name: eslint check
        run: yarn lint
      - name: stylelint check
        run: yarn lint:style
